# Generated by Django 3.2 on 2021-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210417_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.CharField(default='', max_length=400),
        ),
    ]
