# Generated by Django 3.2 on 2021-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group_name',
            field=models.CharField(default='customer', max_length=500),
        ),
    ]
