# Generated by Django 3.2 on 2021-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Dispatched', 'Order Dispatched'), ('In transit', 'In transit'), ('Delivered', 'Delivered')], default='Order Dispached', max_length=20),
        ),
    ]
