# Generated by Django 3.2 on 2021-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group_name',
            field=models.CharField(max_length=500),
        ),
    ]
