# Generated by Django 3.2 on 2021-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OrderPlaced', 'OrderPlaced'), ('OrderDispatched', 'OrderDispatched'), ('Intransit', 'Intransit'), ('Delivered', 'Delivered')], default='Order Placed', max_length=30),
        ),
    ]
