# Generated by Django 3.2 on 2021-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Dispatched', 'Order Dispatched'), ('In transit', 'In transit'), ('Delivered', 'Delivered')], default='Order Placed', max_length=30),
        ),
    ]
