# Generated by Django 3.2 on 2021-04-23 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210424_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_pickup',
            field=models.TimeField(blank=True, default=datetime.time(16, 0)),
        ),
    ]
